#! /bin/sh

sxhkd -c $SXHKD &
if xrandr -q | grep 'VGA-0 connected' > /dev/null; then
    $HOME/.config/bspwm/external.sh &
    bspc monitor HDMI-0 -d I
    bspc monitor VGA-0 -d II III IV V VI VII VIII IX
    bspc config -m HDMI-0  top_padding          27
else 
    bspc monitor -d I II III IV V VI VII VIII IX 
    bspc config top_padding          27
fi

$HOME/.config/polybar/launch.sh &
$HOME/.config/feh/bg.sh &
#picom &

bspc config border_width         0
bspc config window_gap           2 
bspc config split_ratio          0.618
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#2e3440"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
