#! /bin/sh

if xrandr -q | grep 'HDMI-0 connected' > /dev/null; then
    $HOME/.config/bspwm/external.sh &
    bspc monitor HDMI-0 -d I II 
    bspc monitor VGA-0  -d III IV V VI VII VIII IX 
else
    bspc monitor -d I II III IV V VI VII VIII IX 
fi

sxhkd -c $SXHKD &
picom &
$HOME/.config/feh/bg.sh &
$HOME/.config/polybar/launch.sh &

bspc config border_width         0
bspc config window_gap           2 
bspc config split_ratio          0.618
bspc config top_padding          27
bspc config normal_border_color "#2e3440"
bspc config focused_border_color "#2e3440"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
