[workspace]
members = [
	"procs", #3
	"bat",  # 6
	"lsd",  # 17
	"bottom", #32
	"hyperfine", # 74
	"skim", #148
	"exa",  # 297
	"lemoninfo",
	"tock",
	"mdcat",
	"fd",
	"xplr",
]

exclude = [ 
	"starship",
	"leftwm",
    	"ripgrep",
	"broot",
	"sl-rust",
	"rmatrix",
]
