[workspace]
members = [
	"procs",
	"bat",
	"lsd",
	"hyperfine",
	"skim",
	"exa",
	"tock",
	"mdcat",
	"xplr",
	"rmatrix",
	"fd",
	"broot",
	"sl-rust",
]

exclude = [ 
	"lemoninfo",
	"leftwm",
    	"ripgrep",
	"starship",
	"gitui",
	"bottom",
	"lazygit", # go
]
