[workspace]
members = [
	"procs", #3
	"bat",  # 6
	"lsd",  # 17
	"hyperfine", # 74
	"skim", #148
	"exa",  # 297
	"tock",
	"mdcat",
	"xplr",
	"rmatrix",
	"fd",
	"broot",
	"sl-rust",
]

exclude = [ 
	"lemoninfo",
	"leftwm",
    	"ripgrep",
	"starship",
	"gitui",
	"bottom", #32
]
