[package]
name = "lemoninfo"
version = "0.1.0"
authors = ["Kiran Kumar Roy <kkroy22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
sysinfo = "*"
chrono = "*"
